version: "3.8"

services:
  app:
    build:
      context: ../..
      dockerfile: deploy/GPU/Dockerfile
    container_name: gpu-render-server
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]